### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by jlthla** [kmarkley/Indigo-iTunes-Local-Control#2]

**Comment by kmarkley** [comment]
Hi jlthla.  Are you still having an issue?  I got an email about a problem with a playlist, but it looks like you've deleted your comment from github.

**Comment by jlthla** [comment]
So nice of you to reach out.

Yes, I was having a problem with a playlist… seemed some would play, others wouldn’t… but as it turned out, I had moved the entire iTunes library, and it just hadn’t finished finding everything and linking the files, so the songs in the play list couldn’t be found, and that was giving me an error.

LOVE the plug-in.  Trying to get it to slowly fade up from zero on an AirPlay device… had some problems but haven’t really spent much time on trouble shooting, but I’m sure I’ll figure it out.

Thanks again for the checkin.

Cheers

 Jeffrey
